spring:
  application:
    name: provider-server #设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径

server:
  port: 8667

eureka:
  instance:
    hostname: localhost #主机名
    prefer-ip-address: true #将当前实力的ip注册到eureka server中。 默认false 注册主机名
    ip-address: 127.0.0.1 #设置当前实例的ip
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port} #设置控制台现实的实例id
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  #eureka服务端地址，将来客户端使用该地址和eureka进行通信