
server:
  port: 8668

spring:
  application:
    name: consumer-server #设置当前应用的名称。将来会在eureka中Application显示。将来需要使用该名称来获取路径

eureka:
  instance:
    hostname: localhost #主机名

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka